before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: NEiK/S12HYQB6PMb0ebq9lMbP52mcw4zC5vlK2DknEMqpDdMT8vKpbhCI4uYpD0LzXxOZKxwDUyjS2xx3WW72HLBgKOKnKgEQV10VLoQLOt/S2/l6Wqpm0oy/vUes2WnvG4Py+DrUuJGZw3a86ZPtPEEgFJ88lx8vJWJKbsfeV0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: MDZlMzVmNGJiOTA4YjU0M2U2NjNjZWZhOTc1NDIzY2I=P5F3fCwGYqSwVE/b9EQ3jMfmfWW0Ne6rpEeYyXfvLpeYGKhBelbQsMBFpRVeF5EJwL+AZ+F6LJ+jT5nqAt2G3dGRIov+4Yfb6uSJJzNgQfbBkifja75Pdd/82jQ/cU4BV2OAA6Uoi2Q9VYGNxmjJm14RXwIcM/wIpxcXgNTNaRmQbgVeKWLGjQhRLmlH7+KafNZDHGu9s/cIUfIfjlO+iP4mC5Y/vB9QYmUmrgdBBSqIKs2otZczT8/r4uDJs8WrKsnRw377gzpG6Lgr6KeGanBVPI3m3wyx6O73TdJ+dWClfktYLGXx943OFNVwuutlZ6+we03VXvstFrEYYeRtWLrJsvcvtwsklNSh61y3h3Qow7Ws8VYw+W9r5TfLkLOjYThPPegGcp5Z4T6dl61fGvoHZpGOd08HdXuM/FOu78qqSHoFKVjVVR2euZCkCBxfLd2J01Iuu4FqIDfy0TKF3TCWbQ1+YfRhmkFq3ihUNCqSAxJWrB3LfwiWKv42F5/xr7JnILFN82n7PPQsczF+mkGcwQOQhS//YSNwFJSbAGdlWK7adY2EWlDe2f6vdSafbIG38SZbZOvLa6KaixKR5Prcvleh1c9MlVbbYu6zF6WtOa8yh5uvAfl8iw3ftbam/ChRoBeA0630uhMzT10RkjeEDhYtJ1Skx8EMQswj+J6ZBr85qlsXFZ3O3gvCnR+D7rHvZHVtSo3VXExRcaquo0trTNOz3kKcsUDS3bSwS7yURd8FgFPDulVW3fqmxSzbx+bY/3aB3FkjWgrcasHFCYyGQNeUsMezZr21ctzPoa5DaHRVBIg9bYPRei08hxc5fYS8D73MtRNLxP8AlRfpIcd/ElwpGVdKl1urSEGHeOjTToT7TCgJapWR5HM+jp4bJDdDZcWzYXveeGly0d5QSMZ+0suNUrLtRQ7QVwP4XwP0+elJuxuzSm1OVdiO5Vq2Dqwe5l+wQcL7tywI6frsVQ0em8b7YQSuQbaDh46UKjq1p9KIxq17ICwccUGwYLTkmvtMWdFwBYUrm1nzKaRrHYRlvFUbgAca3yQo+6cbGfU3mO6L+lFpcBp7C9SIROgxWqxIlpLAGeu0WVLQS5WGOtAV4bGSXRiQrUmS9w0F6Ehj3GO9KETGjehhyGXDJjTNET3Z238zhrYvZent2o52BazIyc1yGImLb5omT/epYR5An0rqOF6g6b/IEBbiN6XiFaXRZDHsC/ZHlB03Hp0EDmqXtDbky5kVmau3I6yUA2c7ArsHh3mfi2+VI68sqimSqZhyBR+IuEaJF6yimh5OBvlZvewVLaHO0zjk5BNOllXrAn2/lks7UANSKDtOdNONqKwzTdULN3pHuDYMGxTo4gODFHMrF6cZ1+I7NHrz0jJxZDNyLxU7JMz+qeF0H1ea4uiLvUuK3EDXGD5RVvOA4zHg6b4YWmXc2HofQ6R8zRjp4TpSAww/3I5c+F5mhRDGYWq3GjPSo0sfkFOMlPMR/QNXw5/abbQZpdjg0A2I8GpWdrziB3cUb/40HefKyO7pZEefWP6eWXLoWIJ2kwMf2E6u1kwK3i88tpNtOj2UkhZhSMoNcU1uNXRJuENZqUf91KWwHUpJOO8GZXvXKJSXmqtRwq6KDCa220scvJb0r+7s1bwJ2JwibI9EZ1rDVWXJfTzDWNPZ82JaiW//OF25Ow== # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
